### ISSUE TITLE
[BUG] Keyvault access Issue

### ISSUE THREAD

**Issue by prashanthbv12** [Azure/sap-automation#245]
We have enabled the service end point in Virtual netwrk to allow Specific resources such as "Keyvault". And in Netwrking section area we have only enabled to allow the resources with in the Virtual netwrk to by pass the FW.
We are now getting below error in pipeline. Any quick help is appreciated. 

 checking for presence of existing Secret "MGMT-WEEU-LAZ01-sshkey" (Key Vault "https://mgmtweeulaz01user60d.vault.azure.net/"): keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Client address is not authorized and caller is not a trusted service.\r\nClient address: 20.111.13.60\r\nCaller: appid=****************;oid=************************;iss=https://sts.windows.net/f25493ae-1c98-41d7-8a33-0be75f5fe603/\r\nVault: MGMTWEEULAZ01user60D;location=westeurope" InnerError={"code":"ForbiddenByFirewall"}

**Comment by enterprise-1701-d** [comment]
It looks like you are using AzureDevOps. So there are some policies which can work against it.
- access from Internet to keyvaults since AzureDevOps is accessing over the internet in order to create the self hosted agent 
- the keyvault itself has to be changed in the networking section to allow access from all networks (all = includes the internet)
- rerunning the pipeline will not solve it (you have to have the above mentioned setup before the keyvault is created) - so you have to remove the keyvault by hand and let terraform detect, that it is missing or as I did, I changed the tfvars-file for the deployer to add a userkeyvault-arm-id 
`#user_keyvault_id=""
user_keyvault_id="/subscriptions/`
of the aforementioned keyvault, run the pipeline again which will destroy the keyvault and fail, change the tfvars-file back to the original state without the userkeyvault and run the pipeline again. That solved it for me.
