### ISSUE TITLE
[BUG] Pipelines need "git fetch --all" in order to update AzureDevOps repository

### ISSUE THREAD

**Issue by enterprise-1701-d** [Azure/sap-automation#295]
**Describe the bug**
Under special circumstances all Pipelines need a "git fetch --all" in order to update AzureDevOps repository. 
That "git fetch --all " has to be placed before every git checkout <branch name>.
The behaviour was detected now in 2 Azure DevOps environments: 1 customer environment, environment of own organisation
What can be special in Azure DevOps environments to create such a behaviour?

**To reproduce**
Run any pipeline - it runs with "green" results for the first run.
But a second run won't work, since Terraform state and other status files can't be checked in the repository. This leads to new generation of suffixes e.g. for key_vault-names

### Example
Pipeline: Control plane deployment
Phase: Deploy control plane - beginning
```
--- Checkout main ---
error: pathspec 'main' did not match any file(s) known to git
--- Configure devops CLI extension ---

```
at the end

```
--- Update repo ---
fatal: pathspec 'DEPLOYER/MGMT-WEEU-DEP00-INFRASTRUCTURE/terraform.tfstate' did not match any files
fatal: pathspec 'LIBRARY/MGMT-WEEU-SAP_LIBRARY/terraform.tfstate' did not match any files
[detached HEAD 3b578d58] Added updates from devops deployment Control plane deployment [skip ci]
 4 files changed, 115 insertions(+)
 create mode 100644 WORKSPACES/.sap_deployment_automation/MGMTWEEU
 create mode 100644 WORKSPACES/.sap_deployment_automation/MGMTWEEU.md
 create mode 100644 WORKSPACES/DEPLOYER/MGMT-WEEU-DEP00-INFRASTRUCTURE/.terraform/terraform.tfstate
 create mode 100644 WORKSPACES/LIBRARY/MGMT-WEEU-SAP_LIBRARY/.terraform/terraform.tfstate
error: src refspec main does not match any
error: failed to push some refs to 'https://dev.azure.com/<organisation>/<project>/_git/sap-automation'
--- Adding variables to the variable group: SDAF-MGMT ---
```

Workaround:
```
#set a git fetch --all infront of git checkout in every pipeline for every occasion of git checkout
git fetch --all
git checkout -q $(Build.SourceBranchName)
```

**Expected behavior**
should work without it

**Additional context**

**Comment by ErickSegaar** [comment]
We are running on azdo agents and never encountered this issue, only when we run multiple pipelines at the same time due to the commits being done. (btw we currently run on the experimental not on main due to some changes that are required to work for us with private end-pointing and ansible authentication)

Do you run on the default azdo agents? or running on privately hosted ones. When running privately do you have a fresh VM after each stage (should be default behaviour) or do you run persistent vm's. (running persistent VM's gave a lot of issues cause when run in a pool you don't know which one your presented with and what old files remained there from previous execution)
